name: WMInventoryControl
version: '${project.version}'
author: DestroierMariusM/DMariusM
main: destroier.WMInventoryControl.WMInventoryControl
api-version: '1.21'
depend: [WeaponMechanics]
softdepend: [CombatLogX, BlueSlimeCore]
commands:
  wmic:
    description: "Reloads the config file for WMInventoryControl."
    usage: "/wmic reload"
    permission: "wmic.reload"